name: Decorinator
version: '0.1.0'
author: TheNuclearNexus
description: Tool for quickly building decoration assets
minecraft: '1.20'

pipeline:
  - plugins.link_dependencies
  - mecha

require:
  - bolt
  - bolt_expressions

data_pack:
  name: Decorinator
  load:
    - .

resource_pack:
  name: Decorinator RP
  load:
    - .

output: '__dist__'

meta:
  bolt_expressions:
    init_path: 'technical/init'
  dependencies:
    - id: actionbar
      version: 0.4.1
    - id: crafter
      version: 0.2.0